# Site
repository: rgvxsthi/rgvxsthi.github.io
favicon: images/favicon-16x16.png

# Personal info
name: Raghav Sethi
title: User Experience Researcher
email: me@raghavsethi.xyz
website: https://raghavsethi.xyz/

# Social links
linkedin_username: raghavsethi62
github_username: rgvxsthi
instagram_username: sethijii

# About Section
about_profile_image: images/profile3.png
about_content: |
  Hi there! My name's Raghav. I'm a budding UX Researcher and I have recently completed my Masters degree with a specialization in <mark>Human Computer Interaction (HCI)</mark> from The University of Melbourne (QS Ranking #3 in Computer Science).

  While my prior work experience is quite interdisciplinary in nature, a major part of it revolves around research-driven decision making. I'm a strong advocate for user-centric design and believe that it is important to understand and acknowledge the needs and frustrations of your customers to create memorable and easy-to-use experiences for them.

  If you have any questions or would like to consult me for business purposes, please do not hesitate to contact me. I can be reached via email - <a href='mailto:me@raghavsethi.xyz'>me@raghavsethi.xyz</a> or the provided social media handles.

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
#more_title:
#more_content: |
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag