# Site
repository: rgvxsthi/rgvxsthi.github.io
favicon: images/favicon-16x16.png

# Personal info
name: Raghav Sethi
title: User Experience Researcher
email: raghavsethi@yandex.com
#website: rgvxsthi.github.io

# Social links
linkedin_username: raghavsethi62
github_username: rgvxsthi
instagram_username: sethijii

# About Section
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi there! My name's Raghav and I'm a budding UX Researcher.
  
  If you have any questions or would like to consult me for business purposes, please do not hesistate to contact me. I can be reached via email - <a href="mailto:raghavsethi@yandex.com">raghavsethi@yandex.com</a> or the provided social media profiles.

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
#more_title:
#more_content: |
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag