# Site
repository: rgvxsthi/rgvxsthi.github.io
favicon: images/favicon-16x16.png

# Personal info
name: Raghav Sethi
title: User Experience Researcher
email: raghavsethi@yandex.com
website: rgvxsthi.github.io

# Social links
#twitter_username: 
github_username:  rgvxsthi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: raghavsethi62
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
- title: 'Download Resume'
  icon: 'fa-download'
  url: 'rgvxsthi.github.io'

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Raghav and I'm a UX Researcher.

  I am most skilled in: <mark>JavaScript</mark> and <mark>React</mark>.

  As a keen technologist and agile advocate, I have built enterprise software across industries and played an active role in growing an early stage start-up into a well established scale-up. The perfect role is one that encourages strong collaboration with others to create scalable and robust software.

  I enjoy what I do, and take real pride in building things that look great and work well.

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag